repository: bjrjk/BYR-Navi
repository_url: https://github.com/bjrjk/BYR-Navi

timezone: Asia/Shanghai
lang: zh_CN

title: 杰克部落导航
alias_en: Jack-Navi
alias_cn: 杰克部落导航
description: A Navigation Website for Jack
keywords: 杰克部落导航, Jack-Navi, Navi, Navigation
url: https://nav.renjikai.com
established_at: "2020-11-10T00:00+08:00"

author: Jack
author_url: https://renjikai.com
organization: Jack
organization_url: https://renjikai.com
contact: admin[at]renjikai[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
